#Mean,  Sum, Max,  Min,  Last, SumWatt , SumDay

varsToIntegrate = '''
Last: mdl.locTime.Y
Mean: mdl.climate.microclim.RsDif
Mean: mdl.climate.microclim.RsDir
Mean: mdl.climate.microclim.RsUp
Mean: mdl.climate.microclim.RthDw
Mean: mdl.climate.microclim.RthUp
Mean: mdl.climate.microclim.TaC
Sum: mdl.climate.microclim.Rain
Mean: mdl.climate.microclim.d
Sum: mdl.forest.ETR
Sum: mdl.forest.NEE
Mean: mdl.forest.Rnet
Mean: mdl.forest.H
Last: mdl.forest.treeStand.Age
Mean: mdl.forest.treeStand.LeafFall
Mean: mdl.forest.treeStand.SoilRootsWaterPotential
Sum: mdl.forest.treeStand.Rm
Sum: mdl.forest.treeStand.Rg
Mean: mdl.forest.treeStand.BranchSenescence
Mean: mdl.forest.treeStand.RootSenescence
Last: mdl.forest.treeStand.IStress
Last: mdl.forest.treeStand.treesCount
Last: mdl.forest.treeStand.DBHmean
Last: mdl.forest.treeStand.HEIGHTmean
Last: mdl.forest.treeStand.W
Last: mdl.forest.treeStand.Wa
Last: mdl.forest.treeStand.Wr
Last: mdl.forest.treeStand.Wstem
Last: mdl.forest.treeStand.WProducted
Mean: mdl.forest.treeStand.canopy.LAI
Mean: mdl.forest.treeStand.canopy.Rnet
Mean: mdl.forest.treeStand.canopy.H
Sum: mdl.forest.treeStand.canopy.Transpiration
Sum: mdl.forest.treeStand.canopy.Evaporation
Sum: mdl.forest.treeStand.canopy.Assimilation
Sum: mdl.forest.underStorey.Rm
Sum: mdl.forest.underStorey.Rg
Mean: mdl.forest.underStorey.foliage.LitterFall
Mean: mdl.forest.underStorey.roots.LitterFall
Mean: mdl.forest.underStorey.perennial.LitterFall
Max: mdl.forest.underStorey.canopy.LAI
Mean: mdl.forest.underStorey.canopy.Rnet
Mean: mdl.forest.underStorey.canopy.H
Sum: mdl.forest.underStorey.canopy.Transpiration
Sum: mdl.forest.underStorey.canopy.Evaporation
Sum: mdl.forest.underStorey.canopy.Assimilation
Mean: mdl.forest.soil.surface.Rnet
Mean: mdl.forest.soil.surface.H
Sum: mdl.forest.soil.surface.ETR
Mean: mdl.forest.soil.waterCycle.MoistureDeficit
Mean: mdl.forest.soil.waterCycle.RootLayerWaterPotential
Mean: mdl.forest.soil.carbonCycle.Ra
Mean: mdl.forest.soil.carbonCycle.Rh
Last: mdl.forest.soil.carbonCycle.HUM
Last: mdl.forest.soil.carbonCycle.BIO
Last: mdl.forest.soil.carbonCycle.DPM
Last: mdl.forest.soil.carbonCycle.RPM
Last: mdl.forest.soil.carbonCycle.HUM_age
Last: mdl.forest.soil.carbonCycle.BIO_age
Last: mdl.forest.soil.carbonCycle.DPM_age
Last: mdl.forest.soil.carbonCycle.RPM_age
Mean: mdl.manager.harvest_Wstem
Mean: mdl.manager.harvest_Wcrown
Mean: mdl.manager.harvest_Wstub
Mean: mdl.manager.harvest_Wtaproot
Mean: mdl.manager.harvest_Wneedles
'''
